import { NextRequest, NextResponse } from 'next/server';
import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import { getOrCreateAssociatedTokenAccount, mintTo } from '@solana/spl-token';
import bs58 from 'bs58';

export async function POST(request: NextRequest) {
  try {
    const { walletAddress, amount = 10000 } = await request.json();

    if (!walletAddress) {
      return NextResponse.json({ error: 'Wallet address is required' }, { status: 400 });
    }

    const userWallet = new PublicKey(walletAddress);
    const connection = new Connection(process.env.NEXT_PUBLIC_SOLANA_RPC || 'https://api.devnet.solana.com', 'confirmed');
    
    const keyStr = process.env.OPS_WALLET_PRIVATE_KEY;
    if (!keyStr) {
      return NextResponse.json({ error: 'OPS_WALLET_PRIVATE_KEY not configured in environment variables' }, { status: 500 });
    }

    // Parse the private key — supports:
    //   base58 string (what .env.local uses)
    //   JSON uint8 array  e.g. [1,2,3,...]
    //   comma-separated numbers  e.g. "1,2,3,..."
    let secretKeyBytes: Uint8Array;
    if (keyStr.startsWith('[')) {
      secretKeyBytes = new Uint8Array(JSON.parse(keyStr));
    } else if (keyStr.includes(',')) {
      secretKeyBytes = new Uint8Array(keyStr.split(',').map(Number));
    } else {
      // base58 encoded (most common — generated by `solana-keygen` or exported from Phantom)
      secretKeyBytes = bs58.decode(keyStr);
    }

    const payer = Keypair.fromSecretKey(secretKeyBytes);
    const mint = new PublicKey(process.env.NEXT_PUBLIC_IDRX_MINT!);


    // Get or Create ATA
    const ata = await getOrCreateAssociatedTokenAccount(
      connection,
      payer,
      mint,
      userWallet
    );

    // Mint tokens
    const txSignature = await mintTo(
      connection,
      payer,
      mint,
      ata.address,
      payer, // mint authority
      amount * 1_000_000 // Multiply by decimals (6)
    );

    return NextResponse.json({ 
      success: true, 
      txSignature, 
      message: `Minted ${amount} IDRX successfully` 
    });

  } catch (error: any) {
    console.error('Minting error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
